comment:
  layout: header, changes, diff, sunburst
coverage:
  round: down
  precision: 2
  ignore:
    - test
    - doc
    - example
    - src/linpack.f90
    - src/dsparskit.f
  status:
    patch:
      default:
        target: 20%
    project:
      default:
        target: 60%