name = "daskr"
version = "0.1.0"
license = "license"
author = "HugoMVale"
maintainer = "57530119+HugoMVale@users.noreply.github.com"
copyright = "Copyright 2025, HugoMVale"

[build]
auto-executables = false
auto-examples = true
auto-tests = true
module-naming = false

[install]
library = false

[fortran]
implicit-typing = true
implicit-external = true
source-form = "default"
